[job]
dump_folder = "./outputs"
description = "Simplified Llama 3 1B single GPU training"

[profiling]
enable_profiling = false

[metrics]
log_freq = 50
enable_tensorboard = false

[model]
name = "llama3"
flavor = "1B"
tokenizer_path = "./assets/tokenizer/original/tokenizer.model"

[optimizer]
name = "AdamW"
lr = 1e-4  # 根据模型大小调整学习率
eps = 1e-8

[lr_scheduler]
warmup_steps = 50

[training]
batch_size = 4  # 根据显存调整批量大小
seq_len = 1024
max_norm = 1.0
steps = 1000
compile = false
dataset = "c4"

[parallelism]
data_parallel_replicate_degree = 1
data_parallel_shard_degree = -1
tensor_parallel_degree = 1
pipeline_parallel_degree = 1
context_parallel_degree = 1

[checkpoint]
enable_checkpoint = true

[activation_checkpoint]
mode = "none"

[float8]
enable_fsdp_float8_all_gather = false
precompute_float8_dynamic_scale_for_fsdp = false
filter_fqns = ["output"]